apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: staging
    namespace: ""
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
