apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: pgclient
  name: pgclient
  selfLink: /apis/extensions/v1beta1/namespaces/accept/deployments/pgclient
spec:
  replicas: 1
  selector:
    matchLabels:
      run: pgclient
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: pgclient
    spec:
      containers:
      - image: postgres:9.5
        imagePullPolicy: IfNotPresent
        name: pgclient
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
